services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unnamed-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: rootroot

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo 'db.runCommand({ ping: 1 }).ok' | mongosh mongodb://root:secret@127.0.0.1:27017/admin --quiet",
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  novu-api:
    image: "ghcr.io/novuhq/novu/api:2.3.0"
    depends_on:
      - mongodb
      - valkey
    container_name: novu_api
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      API_ROOT_URL: http://localhost:3000
      PORT: 3000
      FRONT_BASE_URL: http://localhost:4000
      MONGO_URL: mongodb://root:secret@mongodb:27017/novu-db?authSource=admin
      MONGO_MIN_POOL_SIZE: 100
      MONGO_MAX_POOL_SIZE: 200
      REDIS_HOST: valkey
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      REDIS_DB_INDEX: 2
      REDIS_CACHE_SERVICE_HOST:
      REDIS_CACHE_SERVICE_PORT:
      S3_LOCAL_STACK:
      S3_BUCKET_NAME:
      S3_REGION:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      JWT_SECRET: super-secret
      STORE_ENCRYPTION_KEY: <ENCRYPTION_KEY_MUST_BE_32_LONG>
      NOVU_SECRET_KEY: <RANDOM_GENERATED_SECRET_KEY>
      SUBSCRIBER_WIDGET_JWT_EXPIRATION_TIME: 15d
      SENTRY_DSN:
      NEW_RELIC_ENABLED: false
      NEW_RELIC_APP_NAME:
      NEW_RELIC_LICENSE_KEY:
      API_CONTEXT_PATH:
      MONGO_AUTO_CREATE_INDEXES: true
      IS_API_IDEMPOTENCY_ENABLED: false
      IS_API_RATE_LIMITING_ENABLED: false
      IS_NEW_MESSAGES_API_RESPONSE_ENABLED: true
      IS_V2_ENABLED: true
      NOVU_TELEMETRY: false
    ports:
      - "3000:3000"

  novu-worker:
    image: "ghcr.io/novuhq/novu/worker:2.3.0"
    depends_on:
      - mongodb
      - valkey
    container_name: novu_worker
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3000
      FRONT_BASE_URL: http://localhost:4000
      MONGO_URL: mongodb://root:secret@mongodb:27017/novu-db?authSource=admin
      MONGO_MIN_POOL_SIZE: 100
      MONGO_MAX_POOL_SIZE: 200
      REDIS_HOST: valkey
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      REDIS_DB_INDEX: 2
      REDIS_CACHE_SERVICE_HOST:
      REDIS_CACHE_SERVICE_PORT:
      S3_LOCAL_STACK:
      S3_BUCKET_NAME:
      S3_REGION:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      JWT_SECRET: super-secret
      STORE_ENCRYPTION_KEY: <ENCRYPTION_KEY_MUST_BE_32_LONG>
      NOVU_SECRET_KEY: <RANDOM_GENERATED_SECRET_KEY>
      SUBSCRIBER_WIDGET_JWT_EXPIRATION_TIME: 15d
      SENTRY_DSN:
      NEW_RELIC_ENABLED: false
      NEW_RELIC_APP_NAME:
      NEW_RELIC_LICENSE_KEY:
      BROADCAST_QUEUE_CHUNK_SIZE: ${BROADCAST_QUEUE_CHUNK_SIZE}
      MULTICAST_QUEUE_CHUNK_SIZE: ${MULTICAST_QUEUE_CHUNK_SIZE}
      API_ROOT_URL: http://novu-api:3000
      IS_EMAIL_INLINE_CSS_DISABLED: false
      IS_USE_MERGED_DIGEST_ID_ENABLED: false
      NOVU_TELEMETRY: false

  novu-ws:
    image: "ghcr.io/novuhq/novu/ws:2.3.0"
    depends_on:
      - mongodb
      - valkey
    container_name: novu_ws
    restart: unless-stopped
    environment:
      PORT: 3002
      NODE_ENV: ${NODE_ENV}
      MONGO_URL: mongodb://root:secret@mongodb:27017/novu-db?authSource=admin
      MONGO_MAX_POOL_SIZE: 100
      REDIS_HOST: valkey
      REDIS_PORT: 6379
      REDIS_PASSWORD:
      JWT_SECRET: super-secret
      WS_CONTEXT_PATH:
      NEW_RELIC_APP_NAME:
      NEW_RELIC_LICENSE_KEY:
      NOVU_TELEMETRY: false
    ports:
      - "3002:3002"

  novu-web:
    image: "ghcr.io/novuhq/novu/dashboard:2.3.0"
    depends_on:
      - novu-api
      - novu-worker
    container_name: novu_web
    restart: unless-stopped
    environment:
      VITE_API_HOSTNAME: http://localhost:3000
      VITE_SELF_HOSTED: true
      VITE_WEBSOCKET_HOSTNAME: http://localhost:3002
      VITE_LEGACY_DASHBOARD_URL: http://localhost:4000
      NOVU_TELEMETRY: false
    ports:
      - "4000:4000"

volumes:
  postgres_data:
  minio_data:
  mongodb_data:
