
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `Organization` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Organization
 * 
 */
export type OrganizationModel = runtime.Types.Result.DefaultSelection<Prisma.$OrganizationPayload>

export type AggregateOrganization = {
  _count: OrganizationCountAggregateOutputType | null
  _avg: OrganizationAvgAggregateOutputType | null
  _sum: OrganizationSumAggregateOutputType | null
  _min: OrganizationMinAggregateOutputType | null
  _max: OrganizationMaxAggregateOutputType | null
}

export type OrganizationAvgAggregateOutputType = {
  reputation: number | null
}

export type OrganizationSumAggregateOutputType = {
  reputation: number | null
}

export type OrganizationMinAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  description: string | null
  logoUrl: string | null
  reputation: number | null
  websiteUrl: string | null
  discordUrl: string | null
  ownerId: string | null
  createdAt: Date | null
}

export type OrganizationMaxAggregateOutputType = {
  id: string | null
  name: string | null
  slug: string | null
  description: string | null
  logoUrl: string | null
  reputation: number | null
  websiteUrl: string | null
  discordUrl: string | null
  ownerId: string | null
  createdAt: Date | null
}

export type OrganizationCountAggregateOutputType = {
  id: number
  name: number
  slug: number
  description: number
  logoUrl: number
  reputation: number
  websiteUrl: number
  discordUrl: number
  ownerId: number
  createdAt: number
  _all: number
}


export type OrganizationAvgAggregateInputType = {
  reputation?: true
}

export type OrganizationSumAggregateInputType = {
  reputation?: true
}

export type OrganizationMinAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  description?: true
  logoUrl?: true
  reputation?: true
  websiteUrl?: true
  discordUrl?: true
  ownerId?: true
  createdAt?: true
}

export type OrganizationMaxAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  description?: true
  logoUrl?: true
  reputation?: true
  websiteUrl?: true
  discordUrl?: true
  ownerId?: true
  createdAt?: true
}

export type OrganizationCountAggregateInputType = {
  id?: true
  name?: true
  slug?: true
  description?: true
  logoUrl?: true
  reputation?: true
  websiteUrl?: true
  discordUrl?: true
  ownerId?: true
  createdAt?: true
  _all?: true
}

export type OrganizationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Organization to aggregate.
   */
  where?: Prisma.OrganizationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Organizations to fetch.
   */
  orderBy?: Prisma.OrganizationOrderByWithRelationInput | Prisma.OrganizationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrganizationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Organizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Organizations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Organizations
  **/
  _count?: true | OrganizationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OrganizationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OrganizationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrganizationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrganizationMaxAggregateInputType
}

export type GetOrganizationAggregateType<T extends OrganizationAggregateArgs> = {
      [P in keyof T & keyof AggregateOrganization]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrganization[P]>
    : Prisma.GetScalarType<T[P], AggregateOrganization[P]>
}




export type OrganizationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrganizationWhereInput
  orderBy?: Prisma.OrganizationOrderByWithAggregationInput | Prisma.OrganizationOrderByWithAggregationInput[]
  by: Prisma.OrganizationScalarFieldEnum[] | Prisma.OrganizationScalarFieldEnum
  having?: Prisma.OrganizationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrganizationCountAggregateInputType | true
  _avg?: OrganizationAvgAggregateInputType
  _sum?: OrganizationSumAggregateInputType
  _min?: OrganizationMinAggregateInputType
  _max?: OrganizationMaxAggregateInputType
}

export type OrganizationGroupByOutputType = {
  id: string
  name: string
  slug: string
  description: string | null
  logoUrl: string | null
  reputation: number
  websiteUrl: string | null
  discordUrl: string | null
  ownerId: string
  createdAt: Date
  _count: OrganizationCountAggregateOutputType | null
  _avg: OrganizationAvgAggregateOutputType | null
  _sum: OrganizationSumAggregateOutputType | null
  _min: OrganizationMinAggregateOutputType | null
  _max: OrganizationMaxAggregateOutputType | null
}

type GetOrganizationGroupByPayload<T extends OrganizationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrganizationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrganizationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrganizationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrganizationGroupByOutputType[P]>
      }
    >
  > 



export type OrganizationWhereInput = {
  AND?: Prisma.OrganizationWhereInput | Prisma.OrganizationWhereInput[]
  OR?: Prisma.OrganizationWhereInput[]
  NOT?: Prisma.OrganizationWhereInput | Prisma.OrganizationWhereInput[]
  id?: Prisma.StringFilter<"Organization"> | string
  name?: Prisma.StringFilter<"Organization"> | string
  slug?: Prisma.StringFilter<"Organization"> | string
  description?: Prisma.StringNullableFilter<"Organization"> | string | null
  logoUrl?: Prisma.StringNullableFilter<"Organization"> | string | null
  reputation?: Prisma.IntFilter<"Organization"> | number
  websiteUrl?: Prisma.StringNullableFilter<"Organization"> | string | null
  discordUrl?: Prisma.StringNullableFilter<"Organization"> | string | null
  ownerId?: Prisma.StringFilter<"Organization"> | string
  createdAt?: Prisma.DateTimeFilter<"Organization"> | Date | string
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  members?: Prisma.OrganizationMemberListRelationFilter
  AuctionListing?: Prisma.AuctionListingListRelationFilter
}

export type OrganizationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  reputation?: Prisma.SortOrder
  websiteUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  discordUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  owner?: Prisma.UserOrderByWithRelationInput
  members?: Prisma.OrganizationMemberOrderByRelationAggregateInput
  AuctionListing?: Prisma.AuctionListingOrderByRelationAggregateInput
}

export type OrganizationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  name?: string
  slug?: string
  AND?: Prisma.OrganizationWhereInput | Prisma.OrganizationWhereInput[]
  OR?: Prisma.OrganizationWhereInput[]
  NOT?: Prisma.OrganizationWhereInput | Prisma.OrganizationWhereInput[]
  description?: Prisma.StringNullableFilter<"Organization"> | string | null
  logoUrl?: Prisma.StringNullableFilter<"Organization"> | string | null
  reputation?: Prisma.IntFilter<"Organization"> | number
  websiteUrl?: Prisma.StringNullableFilter<"Organization"> | string | null
  discordUrl?: Prisma.StringNullableFilter<"Organization"> | string | null
  ownerId?: Prisma.StringFilter<"Organization"> | string
  createdAt?: Prisma.DateTimeFilter<"Organization"> | Date | string
  owner?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  members?: Prisma.OrganizationMemberListRelationFilter
  AuctionListing?: Prisma.AuctionListingListRelationFilter
}, "id" | "name" | "slug">

export type OrganizationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  logoUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  reputation?: Prisma.SortOrder
  websiteUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  discordUrl?: Prisma.SortOrderInput | Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.OrganizationCountOrderByAggregateInput
  _avg?: Prisma.OrganizationAvgOrderByAggregateInput
  _max?: Prisma.OrganizationMaxOrderByAggregateInput
  _min?: Prisma.OrganizationMinOrderByAggregateInput
  _sum?: Prisma.OrganizationSumOrderByAggregateInput
}

export type OrganizationScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrganizationScalarWhereWithAggregatesInput | Prisma.OrganizationScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrganizationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrganizationScalarWhereWithAggregatesInput | Prisma.OrganizationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Organization"> | string
  name?: Prisma.StringWithAggregatesFilter<"Organization"> | string
  slug?: Prisma.StringWithAggregatesFilter<"Organization"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"Organization"> | string | null
  logoUrl?: Prisma.StringNullableWithAggregatesFilter<"Organization"> | string | null
  reputation?: Prisma.IntWithAggregatesFilter<"Organization"> | number
  websiteUrl?: Prisma.StringNullableWithAggregatesFilter<"Organization"> | string | null
  discordUrl?: Prisma.StringNullableWithAggregatesFilter<"Organization"> | string | null
  ownerId?: Prisma.StringWithAggregatesFilter<"Organization"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Organization"> | Date | string
}

export type OrganizationCreateInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  logoUrl?: string | null
  reputation?: number
  websiteUrl?: string | null
  discordUrl?: string | null
  createdAt?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutOwnedOrganizationsInput
  members?: Prisma.OrganizationMemberCreateNestedManyWithoutOrganizationInput
  AuctionListing?: Prisma.AuctionListingCreateNestedManyWithoutOrganizationInput
}

export type OrganizationUncheckedCreateInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  logoUrl?: string | null
  reputation?: number
  websiteUrl?: string | null
  discordUrl?: string | null
  ownerId: string
  createdAt?: Date | string
  members?: Prisma.OrganizationMemberUncheckedCreateNestedManyWithoutOrganizationInput
  AuctionListing?: Prisma.AuctionListingUncheckedCreateNestedManyWithoutOrganizationInput
}

export type OrganizationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reputation?: Prisma.IntFieldUpdateOperationsInput | number
  websiteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discordUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutOwnedOrganizationsNestedInput
  members?: Prisma.OrganizationMemberUpdateManyWithoutOrganizationNestedInput
  AuctionListing?: Prisma.AuctionListingUpdateManyWithoutOrganizationNestedInput
}

export type OrganizationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reputation?: Prisma.IntFieldUpdateOperationsInput | number
  websiteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discordUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  members?: Prisma.OrganizationMemberUncheckedUpdateManyWithoutOrganizationNestedInput
  AuctionListing?: Prisma.AuctionListingUncheckedUpdateManyWithoutOrganizationNestedInput
}

export type OrganizationCreateManyInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  logoUrl?: string | null
  reputation?: number
  websiteUrl?: string | null
  discordUrl?: string | null
  ownerId: string
  createdAt?: Date | string
}

export type OrganizationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reputation?: Prisma.IntFieldUpdateOperationsInput | number
  websiteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discordUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrganizationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reputation?: Prisma.IntFieldUpdateOperationsInput | number
  websiteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discordUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrganizationNullableScalarRelationFilter = {
  is?: Prisma.OrganizationWhereInput | null
  isNot?: Prisma.OrganizationWhereInput | null
}

export type OrganizationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  reputation?: Prisma.SortOrder
  websiteUrl?: Prisma.SortOrder
  discordUrl?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type OrganizationAvgOrderByAggregateInput = {
  reputation?: Prisma.SortOrder
}

export type OrganizationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  reputation?: Prisma.SortOrder
  websiteUrl?: Prisma.SortOrder
  discordUrl?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type OrganizationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  description?: Prisma.SortOrder
  logoUrl?: Prisma.SortOrder
  reputation?: Prisma.SortOrder
  websiteUrl?: Prisma.SortOrder
  discordUrl?: Prisma.SortOrder
  ownerId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type OrganizationSumOrderByAggregateInput = {
  reputation?: Prisma.SortOrder
}

export type OrganizationScalarRelationFilter = {
  is?: Prisma.OrganizationWhereInput
  isNot?: Prisma.OrganizationWhereInput
}

export type OrganizationListRelationFilter = {
  every?: Prisma.OrganizationWhereInput
  some?: Prisma.OrganizationWhereInput
  none?: Prisma.OrganizationWhereInput
}

export type OrganizationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OrganizationCreateNestedOneWithoutAuctionListingInput = {
  create?: Prisma.XOR<Prisma.OrganizationCreateWithoutAuctionListingInput, Prisma.OrganizationUncheckedCreateWithoutAuctionListingInput>
  connectOrCreate?: Prisma.OrganizationCreateOrConnectWithoutAuctionListingInput
  connect?: Prisma.OrganizationWhereUniqueInput
}

export type OrganizationUpdateOneWithoutAuctionListingNestedInput = {
  create?: Prisma.XOR<Prisma.OrganizationCreateWithoutAuctionListingInput, Prisma.OrganizationUncheckedCreateWithoutAuctionListingInput>
  connectOrCreate?: Prisma.OrganizationCreateOrConnectWithoutAuctionListingInput
  upsert?: Prisma.OrganizationUpsertWithoutAuctionListingInput
  disconnect?: Prisma.OrganizationWhereInput | boolean
  delete?: Prisma.OrganizationWhereInput | boolean
  connect?: Prisma.OrganizationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrganizationUpdateToOneWithWhereWithoutAuctionListingInput, Prisma.OrganizationUpdateWithoutAuctionListingInput>, Prisma.OrganizationUncheckedUpdateWithoutAuctionListingInput>
}

export type OrganizationCreateNestedOneWithoutMembersInput = {
  create?: Prisma.XOR<Prisma.OrganizationCreateWithoutMembersInput, Prisma.OrganizationUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.OrganizationCreateOrConnectWithoutMembersInput
  connect?: Prisma.OrganizationWhereUniqueInput
}

export type OrganizationUpdateOneRequiredWithoutMembersNestedInput = {
  create?: Prisma.XOR<Prisma.OrganizationCreateWithoutMembersInput, Prisma.OrganizationUncheckedCreateWithoutMembersInput>
  connectOrCreate?: Prisma.OrganizationCreateOrConnectWithoutMembersInput
  upsert?: Prisma.OrganizationUpsertWithoutMembersInput
  connect?: Prisma.OrganizationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.OrganizationUpdateToOneWithWhereWithoutMembersInput, Prisma.OrganizationUpdateWithoutMembersInput>, Prisma.OrganizationUncheckedUpdateWithoutMembersInput>
}

export type OrganizationCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.OrganizationCreateWithoutOwnerInput, Prisma.OrganizationUncheckedCreateWithoutOwnerInput> | Prisma.OrganizationCreateWithoutOwnerInput[] | Prisma.OrganizationUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.OrganizationCreateOrConnectWithoutOwnerInput | Prisma.OrganizationCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.OrganizationCreateManyOwnerInputEnvelope
  connect?: Prisma.OrganizationWhereUniqueInput | Prisma.OrganizationWhereUniqueInput[]
}

export type OrganizationUncheckedCreateNestedManyWithoutOwnerInput = {
  create?: Prisma.XOR<Prisma.OrganizationCreateWithoutOwnerInput, Prisma.OrganizationUncheckedCreateWithoutOwnerInput> | Prisma.OrganizationCreateWithoutOwnerInput[] | Prisma.OrganizationUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.OrganizationCreateOrConnectWithoutOwnerInput | Prisma.OrganizationCreateOrConnectWithoutOwnerInput[]
  createMany?: Prisma.OrganizationCreateManyOwnerInputEnvelope
  connect?: Prisma.OrganizationWhereUniqueInput | Prisma.OrganizationWhereUniqueInput[]
}

export type OrganizationUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.OrganizationCreateWithoutOwnerInput, Prisma.OrganizationUncheckedCreateWithoutOwnerInput> | Prisma.OrganizationCreateWithoutOwnerInput[] | Prisma.OrganizationUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.OrganizationCreateOrConnectWithoutOwnerInput | Prisma.OrganizationCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.OrganizationUpsertWithWhereUniqueWithoutOwnerInput | Prisma.OrganizationUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.OrganizationCreateManyOwnerInputEnvelope
  set?: Prisma.OrganizationWhereUniqueInput | Prisma.OrganizationWhereUniqueInput[]
  disconnect?: Prisma.OrganizationWhereUniqueInput | Prisma.OrganizationWhereUniqueInput[]
  delete?: Prisma.OrganizationWhereUniqueInput | Prisma.OrganizationWhereUniqueInput[]
  connect?: Prisma.OrganizationWhereUniqueInput | Prisma.OrganizationWhereUniqueInput[]
  update?: Prisma.OrganizationUpdateWithWhereUniqueWithoutOwnerInput | Prisma.OrganizationUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.OrganizationUpdateManyWithWhereWithoutOwnerInput | Prisma.OrganizationUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.OrganizationScalarWhereInput | Prisma.OrganizationScalarWhereInput[]
}

export type OrganizationUncheckedUpdateManyWithoutOwnerNestedInput = {
  create?: Prisma.XOR<Prisma.OrganizationCreateWithoutOwnerInput, Prisma.OrganizationUncheckedCreateWithoutOwnerInput> | Prisma.OrganizationCreateWithoutOwnerInput[] | Prisma.OrganizationUncheckedCreateWithoutOwnerInput[]
  connectOrCreate?: Prisma.OrganizationCreateOrConnectWithoutOwnerInput | Prisma.OrganizationCreateOrConnectWithoutOwnerInput[]
  upsert?: Prisma.OrganizationUpsertWithWhereUniqueWithoutOwnerInput | Prisma.OrganizationUpsertWithWhereUniqueWithoutOwnerInput[]
  createMany?: Prisma.OrganizationCreateManyOwnerInputEnvelope
  set?: Prisma.OrganizationWhereUniqueInput | Prisma.OrganizationWhereUniqueInput[]
  disconnect?: Prisma.OrganizationWhereUniqueInput | Prisma.OrganizationWhereUniqueInput[]
  delete?: Prisma.OrganizationWhereUniqueInput | Prisma.OrganizationWhereUniqueInput[]
  connect?: Prisma.OrganizationWhereUniqueInput | Prisma.OrganizationWhereUniqueInput[]
  update?: Prisma.OrganizationUpdateWithWhereUniqueWithoutOwnerInput | Prisma.OrganizationUpdateWithWhereUniqueWithoutOwnerInput[]
  updateMany?: Prisma.OrganizationUpdateManyWithWhereWithoutOwnerInput | Prisma.OrganizationUpdateManyWithWhereWithoutOwnerInput[]
  deleteMany?: Prisma.OrganizationScalarWhereInput | Prisma.OrganizationScalarWhereInput[]
}

export type OrganizationCreateWithoutAuctionListingInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  logoUrl?: string | null
  reputation?: number
  websiteUrl?: string | null
  discordUrl?: string | null
  createdAt?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutOwnedOrganizationsInput
  members?: Prisma.OrganizationMemberCreateNestedManyWithoutOrganizationInput
}

export type OrganizationUncheckedCreateWithoutAuctionListingInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  logoUrl?: string | null
  reputation?: number
  websiteUrl?: string | null
  discordUrl?: string | null
  ownerId: string
  createdAt?: Date | string
  members?: Prisma.OrganizationMemberUncheckedCreateNestedManyWithoutOrganizationInput
}

export type OrganizationCreateOrConnectWithoutAuctionListingInput = {
  where: Prisma.OrganizationWhereUniqueInput
  create: Prisma.XOR<Prisma.OrganizationCreateWithoutAuctionListingInput, Prisma.OrganizationUncheckedCreateWithoutAuctionListingInput>
}

export type OrganizationUpsertWithoutAuctionListingInput = {
  update: Prisma.XOR<Prisma.OrganizationUpdateWithoutAuctionListingInput, Prisma.OrganizationUncheckedUpdateWithoutAuctionListingInput>
  create: Prisma.XOR<Prisma.OrganizationCreateWithoutAuctionListingInput, Prisma.OrganizationUncheckedCreateWithoutAuctionListingInput>
  where?: Prisma.OrganizationWhereInput
}

export type OrganizationUpdateToOneWithWhereWithoutAuctionListingInput = {
  where?: Prisma.OrganizationWhereInput
  data: Prisma.XOR<Prisma.OrganizationUpdateWithoutAuctionListingInput, Prisma.OrganizationUncheckedUpdateWithoutAuctionListingInput>
}

export type OrganizationUpdateWithoutAuctionListingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reputation?: Prisma.IntFieldUpdateOperationsInput | number
  websiteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discordUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutOwnedOrganizationsNestedInput
  members?: Prisma.OrganizationMemberUpdateManyWithoutOrganizationNestedInput
}

export type OrganizationUncheckedUpdateWithoutAuctionListingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reputation?: Prisma.IntFieldUpdateOperationsInput | number
  websiteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discordUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  members?: Prisma.OrganizationMemberUncheckedUpdateManyWithoutOrganizationNestedInput
}

export type OrganizationCreateWithoutMembersInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  logoUrl?: string | null
  reputation?: number
  websiteUrl?: string | null
  discordUrl?: string | null
  createdAt?: Date | string
  owner: Prisma.UserCreateNestedOneWithoutOwnedOrganizationsInput
  AuctionListing?: Prisma.AuctionListingCreateNestedManyWithoutOrganizationInput
}

export type OrganizationUncheckedCreateWithoutMembersInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  logoUrl?: string | null
  reputation?: number
  websiteUrl?: string | null
  discordUrl?: string | null
  ownerId: string
  createdAt?: Date | string
  AuctionListing?: Prisma.AuctionListingUncheckedCreateNestedManyWithoutOrganizationInput
}

export type OrganizationCreateOrConnectWithoutMembersInput = {
  where: Prisma.OrganizationWhereUniqueInput
  create: Prisma.XOR<Prisma.OrganizationCreateWithoutMembersInput, Prisma.OrganizationUncheckedCreateWithoutMembersInput>
}

export type OrganizationUpsertWithoutMembersInput = {
  update: Prisma.XOR<Prisma.OrganizationUpdateWithoutMembersInput, Prisma.OrganizationUncheckedUpdateWithoutMembersInput>
  create: Prisma.XOR<Prisma.OrganizationCreateWithoutMembersInput, Prisma.OrganizationUncheckedCreateWithoutMembersInput>
  where?: Prisma.OrganizationWhereInput
}

export type OrganizationUpdateToOneWithWhereWithoutMembersInput = {
  where?: Prisma.OrganizationWhereInput
  data: Prisma.XOR<Prisma.OrganizationUpdateWithoutMembersInput, Prisma.OrganizationUncheckedUpdateWithoutMembersInput>
}

export type OrganizationUpdateWithoutMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reputation?: Prisma.IntFieldUpdateOperationsInput | number
  websiteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discordUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  owner?: Prisma.UserUpdateOneRequiredWithoutOwnedOrganizationsNestedInput
  AuctionListing?: Prisma.AuctionListingUpdateManyWithoutOrganizationNestedInput
}

export type OrganizationUncheckedUpdateWithoutMembersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reputation?: Prisma.IntFieldUpdateOperationsInput | number
  websiteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discordUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  ownerId?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  AuctionListing?: Prisma.AuctionListingUncheckedUpdateManyWithoutOrganizationNestedInput
}

export type OrganizationCreateWithoutOwnerInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  logoUrl?: string | null
  reputation?: number
  websiteUrl?: string | null
  discordUrl?: string | null
  createdAt?: Date | string
  members?: Prisma.OrganizationMemberCreateNestedManyWithoutOrganizationInput
  AuctionListing?: Prisma.AuctionListingCreateNestedManyWithoutOrganizationInput
}

export type OrganizationUncheckedCreateWithoutOwnerInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  logoUrl?: string | null
  reputation?: number
  websiteUrl?: string | null
  discordUrl?: string | null
  createdAt?: Date | string
  members?: Prisma.OrganizationMemberUncheckedCreateNestedManyWithoutOrganizationInput
  AuctionListing?: Prisma.AuctionListingUncheckedCreateNestedManyWithoutOrganizationInput
}

export type OrganizationCreateOrConnectWithoutOwnerInput = {
  where: Prisma.OrganizationWhereUniqueInput
  create: Prisma.XOR<Prisma.OrganizationCreateWithoutOwnerInput, Prisma.OrganizationUncheckedCreateWithoutOwnerInput>
}

export type OrganizationCreateManyOwnerInputEnvelope = {
  data: Prisma.OrganizationCreateManyOwnerInput | Prisma.OrganizationCreateManyOwnerInput[]
  skipDuplicates?: boolean
}

export type OrganizationUpsertWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.OrganizationWhereUniqueInput
  update: Prisma.XOR<Prisma.OrganizationUpdateWithoutOwnerInput, Prisma.OrganizationUncheckedUpdateWithoutOwnerInput>
  create: Prisma.XOR<Prisma.OrganizationCreateWithoutOwnerInput, Prisma.OrganizationUncheckedCreateWithoutOwnerInput>
}

export type OrganizationUpdateWithWhereUniqueWithoutOwnerInput = {
  where: Prisma.OrganizationWhereUniqueInput
  data: Prisma.XOR<Prisma.OrganizationUpdateWithoutOwnerInput, Prisma.OrganizationUncheckedUpdateWithoutOwnerInput>
}

export type OrganizationUpdateManyWithWhereWithoutOwnerInput = {
  where: Prisma.OrganizationScalarWhereInput
  data: Prisma.XOR<Prisma.OrganizationUpdateManyMutationInput, Prisma.OrganizationUncheckedUpdateManyWithoutOwnerInput>
}

export type OrganizationScalarWhereInput = {
  AND?: Prisma.OrganizationScalarWhereInput | Prisma.OrganizationScalarWhereInput[]
  OR?: Prisma.OrganizationScalarWhereInput[]
  NOT?: Prisma.OrganizationScalarWhereInput | Prisma.OrganizationScalarWhereInput[]
  id?: Prisma.StringFilter<"Organization"> | string
  name?: Prisma.StringFilter<"Organization"> | string
  slug?: Prisma.StringFilter<"Organization"> | string
  description?: Prisma.StringNullableFilter<"Organization"> | string | null
  logoUrl?: Prisma.StringNullableFilter<"Organization"> | string | null
  reputation?: Prisma.IntFilter<"Organization"> | number
  websiteUrl?: Prisma.StringNullableFilter<"Organization"> | string | null
  discordUrl?: Prisma.StringNullableFilter<"Organization"> | string | null
  ownerId?: Prisma.StringFilter<"Organization"> | string
  createdAt?: Prisma.DateTimeFilter<"Organization"> | Date | string
}

export type OrganizationCreateManyOwnerInput = {
  id?: string
  name: string
  slug: string
  description?: string | null
  logoUrl?: string | null
  reputation?: number
  websiteUrl?: string | null
  discordUrl?: string | null
  createdAt?: Date | string
}

export type OrganizationUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reputation?: Prisma.IntFieldUpdateOperationsInput | number
  websiteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discordUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  members?: Prisma.OrganizationMemberUpdateManyWithoutOrganizationNestedInput
  AuctionListing?: Prisma.AuctionListingUpdateManyWithoutOrganizationNestedInput
}

export type OrganizationUncheckedUpdateWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reputation?: Prisma.IntFieldUpdateOperationsInput | number
  websiteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discordUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  members?: Prisma.OrganizationMemberUncheckedUpdateManyWithoutOrganizationNestedInput
  AuctionListing?: Prisma.AuctionListingUncheckedUpdateManyWithoutOrganizationNestedInput
}

export type OrganizationUncheckedUpdateManyWithoutOwnerInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  logoUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reputation?: Prisma.IntFieldUpdateOperationsInput | number
  websiteUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  discordUrl?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type OrganizationCountOutputType
 */

export type OrganizationCountOutputType = {
  members: number
  AuctionListing: number
}

export type OrganizationCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  members?: boolean | OrganizationCountOutputTypeCountMembersArgs
  AuctionListing?: boolean | OrganizationCountOutputTypeCountAuctionListingArgs
}

/**
 * OrganizationCountOutputType without action
 */
export type OrganizationCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationCountOutputType
   */
  select?: Prisma.OrganizationCountOutputTypeSelect<ExtArgs> | null
}

/**
 * OrganizationCountOutputType without action
 */
export type OrganizationCountOutputTypeCountMembersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrganizationMemberWhereInput
}

/**
 * OrganizationCountOutputType without action
 */
export type OrganizationCountOutputTypeCountAuctionListingArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuctionListingWhereInput
}


export type OrganizationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  logoUrl?: boolean
  reputation?: boolean
  websiteUrl?: boolean
  discordUrl?: boolean
  ownerId?: boolean
  createdAt?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  members?: boolean | Prisma.Organization$membersArgs<ExtArgs>
  AuctionListing?: boolean | Prisma.Organization$AuctionListingArgs<ExtArgs>
  _count?: boolean | Prisma.OrganizationCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["organization"]>

export type OrganizationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  logoUrl?: boolean
  reputation?: boolean
  websiteUrl?: boolean
  discordUrl?: boolean
  ownerId?: boolean
  createdAt?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["organization"]>

export type OrganizationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  logoUrl?: boolean
  reputation?: boolean
  websiteUrl?: boolean
  discordUrl?: boolean
  ownerId?: boolean
  createdAt?: boolean
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["organization"]>

export type OrganizationSelectScalar = {
  id?: boolean
  name?: boolean
  slug?: boolean
  description?: boolean
  logoUrl?: boolean
  reputation?: boolean
  websiteUrl?: boolean
  discordUrl?: boolean
  ownerId?: boolean
  createdAt?: boolean
}

export type OrganizationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "slug" | "description" | "logoUrl" | "reputation" | "websiteUrl" | "discordUrl" | "ownerId" | "createdAt", ExtArgs["result"]["organization"]>
export type OrganizationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  members?: boolean | Prisma.Organization$membersArgs<ExtArgs>
  AuctionListing?: boolean | Prisma.Organization$AuctionListingArgs<ExtArgs>
  _count?: boolean | Prisma.OrganizationCountOutputTypeDefaultArgs<ExtArgs>
}
export type OrganizationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type OrganizationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  owner?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $OrganizationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Organization"
  objects: {
    owner: Prisma.$UserPayload<ExtArgs>
    members: Prisma.$OrganizationMemberPayload<ExtArgs>[]
    AuctionListing: Prisma.$AuctionListingPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    slug: string
    description: string | null
    logoUrl: string | null
    reputation: number
    websiteUrl: string | null
    discordUrl: string | null
    ownerId: string
    createdAt: Date
  }, ExtArgs["result"]["organization"]>
  composites: {}
}

export type OrganizationGetPayload<S extends boolean | null | undefined | OrganizationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrganizationPayload, S>

export type OrganizationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrganizationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: OrganizationCountAggregateInputType | true
  }

export interface OrganizationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Organization'], meta: { name: 'Organization' } }
  /**
   * Find zero or one Organization that matches the filter.
   * @param {OrganizationFindUniqueArgs} args - Arguments to find a Organization
   * @example
   * // Get one Organization
   * const organization = await prisma.organization.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrganizationFindUniqueArgs>(args: Prisma.SelectSubset<T, OrganizationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Organization that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrganizationFindUniqueOrThrowArgs} args - Arguments to find a Organization
   * @example
   * // Get one Organization
   * const organization = await prisma.organization.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrganizationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrganizationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Organization that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationFindFirstArgs} args - Arguments to find a Organization
   * @example
   * // Get one Organization
   * const organization = await prisma.organization.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrganizationFindFirstArgs>(args?: Prisma.SelectSubset<T, OrganizationFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Organization that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationFindFirstOrThrowArgs} args - Arguments to find a Organization
   * @example
   * // Get one Organization
   * const organization = await prisma.organization.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrganizationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrganizationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Organizations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Organizations
   * const organizations = await prisma.organization.findMany()
   * 
   * // Get first 10 Organizations
   * const organizations = await prisma.organization.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const organizationWithIdOnly = await prisma.organization.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrganizationFindManyArgs>(args?: Prisma.SelectSubset<T, OrganizationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Organization.
   * @param {OrganizationCreateArgs} args - Arguments to create a Organization.
   * @example
   * // Create one Organization
   * const Organization = await prisma.organization.create({
   *   data: {
   *     // ... data to create a Organization
   *   }
   * })
   * 
   */
  create<T extends OrganizationCreateArgs>(args: Prisma.SelectSubset<T, OrganizationCreateArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Organizations.
   * @param {OrganizationCreateManyArgs} args - Arguments to create many Organizations.
   * @example
   * // Create many Organizations
   * const organization = await prisma.organization.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrganizationCreateManyArgs>(args?: Prisma.SelectSubset<T, OrganizationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Organizations and returns the data saved in the database.
   * @param {OrganizationCreateManyAndReturnArgs} args - Arguments to create many Organizations.
   * @example
   * // Create many Organizations
   * const organization = await prisma.organization.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Organizations and only return the `id`
   * const organizationWithIdOnly = await prisma.organization.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends OrganizationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, OrganizationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Organization.
   * @param {OrganizationDeleteArgs} args - Arguments to delete one Organization.
   * @example
   * // Delete one Organization
   * const Organization = await prisma.organization.delete({
   *   where: {
   *     // ... filter to delete one Organization
   *   }
   * })
   * 
   */
  delete<T extends OrganizationDeleteArgs>(args: Prisma.SelectSubset<T, OrganizationDeleteArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Organization.
   * @param {OrganizationUpdateArgs} args - Arguments to update one Organization.
   * @example
   * // Update one Organization
   * const organization = await prisma.organization.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrganizationUpdateArgs>(args: Prisma.SelectSubset<T, OrganizationUpdateArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Organizations.
   * @param {OrganizationDeleteManyArgs} args - Arguments to filter Organizations to delete.
   * @example
   * // Delete a few Organizations
   * const { count } = await prisma.organization.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrganizationDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrganizationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Organizations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Organizations
   * const organization = await prisma.organization.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrganizationUpdateManyArgs>(args: Prisma.SelectSubset<T, OrganizationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Organizations and returns the data updated in the database.
   * @param {OrganizationUpdateManyAndReturnArgs} args - Arguments to update many Organizations.
   * @example
   * // Update many Organizations
   * const organization = await prisma.organization.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Organizations and only return the `id`
   * const organizationWithIdOnly = await prisma.organization.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends OrganizationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, OrganizationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Organization.
   * @param {OrganizationUpsertArgs} args - Arguments to update or create a Organization.
   * @example
   * // Update or create a Organization
   * const organization = await prisma.organization.upsert({
   *   create: {
   *     // ... data to create a Organization
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Organization we want to update
   *   }
   * })
   */
  upsert<T extends OrganizationUpsertArgs>(args: Prisma.SelectSubset<T, OrganizationUpsertArgs<ExtArgs>>): Prisma.Prisma__OrganizationClient<runtime.Types.Result.GetResult<Prisma.$OrganizationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Organizations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationCountArgs} args - Arguments to filter Organizations to count.
   * @example
   * // Count the number of Organizations
   * const count = await prisma.organization.count({
   *   where: {
   *     // ... the filter for the Organizations we want to count
   *   }
   * })
  **/
  count<T extends OrganizationCountArgs>(
    args?: Prisma.Subset<T, OrganizationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrganizationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Organization.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrganizationAggregateArgs>(args: Prisma.Subset<T, OrganizationAggregateArgs>): Prisma.PrismaPromise<GetOrganizationAggregateType<T>>

  /**
   * Group by Organization.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrganizationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrganizationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrganizationGroupByArgs['orderBy'] }
      : { orderBy?: OrganizationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrganizationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrganizationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Organization model
 */
readonly fields: OrganizationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Organization.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrganizationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  owner<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  members<T extends Prisma.Organization$membersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Organization$membersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrganizationMemberPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  AuctionListing<T extends Prisma.Organization$AuctionListingArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Organization$AuctionListingArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuctionListingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Organization model
 */
export interface OrganizationFieldRefs {
  readonly id: Prisma.FieldRef<"Organization", 'String'>
  readonly name: Prisma.FieldRef<"Organization", 'String'>
  readonly slug: Prisma.FieldRef<"Organization", 'String'>
  readonly description: Prisma.FieldRef<"Organization", 'String'>
  readonly logoUrl: Prisma.FieldRef<"Organization", 'String'>
  readonly reputation: Prisma.FieldRef<"Organization", 'Int'>
  readonly websiteUrl: Prisma.FieldRef<"Organization", 'String'>
  readonly discordUrl: Prisma.FieldRef<"Organization", 'String'>
  readonly ownerId: Prisma.FieldRef<"Organization", 'String'>
  readonly createdAt: Prisma.FieldRef<"Organization", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Organization findUnique
 */
export type OrganizationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInclude<ExtArgs> | null
  /**
   * Filter, which Organization to fetch.
   */
  where: Prisma.OrganizationWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Organization findUniqueOrThrow
 */
export type OrganizationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInclude<ExtArgs> | null
  /**
   * Filter, which Organization to fetch.
   */
  where: Prisma.OrganizationWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Organization findFirst
 */
export type OrganizationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInclude<ExtArgs> | null
  /**
   * Filter, which Organization to fetch.
   */
  where?: Prisma.OrganizationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Organizations to fetch.
   */
  orderBy?: Prisma.OrganizationOrderByWithRelationInput | Prisma.OrganizationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Organizations.
   */
  cursor?: Prisma.OrganizationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Organizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Organizations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Organizations.
   */
  distinct?: Prisma.OrganizationScalarFieldEnum | Prisma.OrganizationScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Organization findFirstOrThrow
 */
export type OrganizationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInclude<ExtArgs> | null
  /**
   * Filter, which Organization to fetch.
   */
  where?: Prisma.OrganizationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Organizations to fetch.
   */
  orderBy?: Prisma.OrganizationOrderByWithRelationInput | Prisma.OrganizationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Organizations.
   */
  cursor?: Prisma.OrganizationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Organizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Organizations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Organizations.
   */
  distinct?: Prisma.OrganizationScalarFieldEnum | Prisma.OrganizationScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Organization findMany
 */
export type OrganizationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInclude<ExtArgs> | null
  /**
   * Filter, which Organizations to fetch.
   */
  where?: Prisma.OrganizationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Organizations to fetch.
   */
  orderBy?: Prisma.OrganizationOrderByWithRelationInput | Prisma.OrganizationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Organizations.
   */
  cursor?: Prisma.OrganizationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Organizations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Organizations.
   */
  skip?: number
  distinct?: Prisma.OrganizationScalarFieldEnum | Prisma.OrganizationScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Organization create
 */
export type OrganizationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInclude<ExtArgs> | null
  /**
   * The data needed to create a Organization.
   */
  data: Prisma.XOR<Prisma.OrganizationCreateInput, Prisma.OrganizationUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Organization createMany
 */
export type OrganizationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Organizations.
   */
  data: Prisma.OrganizationCreateManyInput | Prisma.OrganizationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Organization createManyAndReturn
 */
export type OrganizationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * The data used to create many Organizations.
   */
  data: Prisma.OrganizationCreateManyInput | Prisma.OrganizationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Organization update
 */
export type OrganizationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInclude<ExtArgs> | null
  /**
   * The data needed to update a Organization.
   */
  data: Prisma.XOR<Prisma.OrganizationUpdateInput, Prisma.OrganizationUncheckedUpdateInput>
  /**
   * Choose, which Organization to update.
   */
  where: Prisma.OrganizationWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Organization updateMany
 */
export type OrganizationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Organizations.
   */
  data: Prisma.XOR<Prisma.OrganizationUpdateManyMutationInput, Prisma.OrganizationUncheckedUpdateManyInput>
  /**
   * Filter which Organizations to update
   */
  where?: Prisma.OrganizationWhereInput
  /**
   * Limit how many Organizations to update.
   */
  limit?: number
}

/**
 * Organization updateManyAndReturn
 */
export type OrganizationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * The data used to update Organizations.
   */
  data: Prisma.XOR<Prisma.OrganizationUpdateManyMutationInput, Prisma.OrganizationUncheckedUpdateManyInput>
  /**
   * Filter which Organizations to update
   */
  where?: Prisma.OrganizationWhereInput
  /**
   * Limit how many Organizations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Organization upsert
 */
export type OrganizationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInclude<ExtArgs> | null
  /**
   * The filter to search for the Organization to update in case it exists.
   */
  where: Prisma.OrganizationWhereUniqueInput
  /**
   * In case the Organization found by the `where` argument doesn't exist, create a new Organization with this data.
   */
  create: Prisma.XOR<Prisma.OrganizationCreateInput, Prisma.OrganizationUncheckedCreateInput>
  /**
   * In case the Organization was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrganizationUpdateInput, Prisma.OrganizationUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Organization delete
 */
export type OrganizationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInclude<ExtArgs> | null
  /**
   * Filter which Organization to delete.
   */
  where: Prisma.OrganizationWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * Organization deleteMany
 */
export type OrganizationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Organizations to delete
   */
  where?: Prisma.OrganizationWhereInput
  /**
   * Limit how many Organizations to delete.
   */
  limit?: number
}

/**
 * Organization.members
 */
export type Organization$membersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the OrganizationMember
   */
  select?: Prisma.OrganizationMemberSelect<ExtArgs> | null
  /**
   * Omit specific fields from the OrganizationMember
   */
  omit?: Prisma.OrganizationMemberOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationMemberInclude<ExtArgs> | null
  where?: Prisma.OrganizationMemberWhereInput
  orderBy?: Prisma.OrganizationMemberOrderByWithRelationInput | Prisma.OrganizationMemberOrderByWithRelationInput[]
  cursor?: Prisma.OrganizationMemberWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.OrganizationMemberScalarFieldEnum | Prisma.OrganizationMemberScalarFieldEnum[]
}

/**
 * Organization.AuctionListing
 */
export type Organization$AuctionListingArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListing
   */
  select?: Prisma.AuctionListingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListing
   */
  omit?: Prisma.AuctionListingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingInclude<ExtArgs> | null
  where?: Prisma.AuctionListingWhereInput
  orderBy?: Prisma.AuctionListingOrderByWithRelationInput | Prisma.AuctionListingOrderByWithRelationInput[]
  cursor?: Prisma.AuctionListingWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AuctionListingScalarFieldEnum | Prisma.AuctionListingScalarFieldEnum[]
}

/**
 * Organization without action
 */
export type OrganizationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Organization
   */
  select?: Prisma.OrganizationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Organization
   */
  omit?: Prisma.OrganizationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrganizationInclude<ExtArgs> | null
}
