
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/**
 * This file exports the `AuctionListingItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model AuctionListingItem
 * 
 */
export type AuctionListingItemModel = runtime.Types.Result.DefaultSelection<Prisma.$AuctionListingItemPayload>

export type AggregateAuctionListingItem = {
  _count: AuctionListingItemCountAggregateOutputType | null
  _avg: AuctionListingItemAvgAggregateOutputType | null
  _sum: AuctionListingItemSumAggregateOutputType | null
  _min: AuctionListingItemMinAggregateOutputType | null
  _max: AuctionListingItemMaxAggregateOutputType | null
}

export type AuctionListingItemAvgAggregateOutputType = {
  quantity: number | null
}

export type AuctionListingItemSumAggregateOutputType = {
  quantity: number | null
}

export type AuctionListingItemMinAggregateOutputType = {
  id: string | null
  listingId: string | null
  entityId: string | null
  name: string | null
  quantity: number | null
  uuu: boolean | null
  unique: boolean | null
  customName: string | null
  customImage: string | null
  imported: boolean | null
  createdAt: Date | null
}

export type AuctionListingItemMaxAggregateOutputType = {
  id: string | null
  listingId: string | null
  entityId: string | null
  name: string | null
  quantity: number | null
  uuu: boolean | null
  unique: boolean | null
  customName: string | null
  customImage: string | null
  imported: boolean | null
  createdAt: Date | null
}

export type AuctionListingItemCountAggregateOutputType = {
  id: number
  listingId: number
  entityId: number
  name: number
  quantity: number
  uuu: number
  unique: number
  customName: number
  customImage: number
  imported: number
  createdAt: number
  _all: number
}


export type AuctionListingItemAvgAggregateInputType = {
  quantity?: true
}

export type AuctionListingItemSumAggregateInputType = {
  quantity?: true
}

export type AuctionListingItemMinAggregateInputType = {
  id?: true
  listingId?: true
  entityId?: true
  name?: true
  quantity?: true
  uuu?: true
  unique?: true
  customName?: true
  customImage?: true
  imported?: true
  createdAt?: true
}

export type AuctionListingItemMaxAggregateInputType = {
  id?: true
  listingId?: true
  entityId?: true
  name?: true
  quantity?: true
  uuu?: true
  unique?: true
  customName?: true
  customImage?: true
  imported?: true
  createdAt?: true
}

export type AuctionListingItemCountAggregateInputType = {
  id?: true
  listingId?: true
  entityId?: true
  name?: true
  quantity?: true
  uuu?: true
  unique?: true
  customName?: true
  customImage?: true
  imported?: true
  createdAt?: true
  _all?: true
}

export type AuctionListingItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuctionListingItem to aggregate.
   */
  where?: Prisma.AuctionListingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuctionListingItems to fetch.
   */
  orderBy?: Prisma.AuctionListingItemOrderByWithRelationInput | Prisma.AuctionListingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AuctionListingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuctionListingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuctionListingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AuctionListingItems
  **/
  _count?: true | AuctionListingItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AuctionListingItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AuctionListingItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AuctionListingItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AuctionListingItemMaxAggregateInputType
}

export type GetAuctionListingItemAggregateType<T extends AuctionListingItemAggregateArgs> = {
      [P in keyof T & keyof AggregateAuctionListingItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAuctionListingItem[P]>
    : Prisma.GetScalarType<T[P], AggregateAuctionListingItem[P]>
}




export type AuctionListingItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AuctionListingItemWhereInput
  orderBy?: Prisma.AuctionListingItemOrderByWithAggregationInput | Prisma.AuctionListingItemOrderByWithAggregationInput[]
  by: Prisma.AuctionListingItemScalarFieldEnum[] | Prisma.AuctionListingItemScalarFieldEnum
  having?: Prisma.AuctionListingItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AuctionListingItemCountAggregateInputType | true
  _avg?: AuctionListingItemAvgAggregateInputType
  _sum?: AuctionListingItemSumAggregateInputType
  _min?: AuctionListingItemMinAggregateInputType
  _max?: AuctionListingItemMaxAggregateInputType
}

export type AuctionListingItemGroupByOutputType = {
  id: string
  listingId: string
  entityId: string
  name: string
  quantity: number
  uuu: boolean
  unique: boolean
  customName: string | null
  customImage: string | null
  imported: boolean
  createdAt: Date
  _count: AuctionListingItemCountAggregateOutputType | null
  _avg: AuctionListingItemAvgAggregateOutputType | null
  _sum: AuctionListingItemSumAggregateOutputType | null
  _min: AuctionListingItemMinAggregateOutputType | null
  _max: AuctionListingItemMaxAggregateOutputType | null
}

type GetAuctionListingItemGroupByPayload<T extends AuctionListingItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AuctionListingItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AuctionListingItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AuctionListingItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AuctionListingItemGroupByOutputType[P]>
      }
    >
  > 



export type AuctionListingItemWhereInput = {
  AND?: Prisma.AuctionListingItemWhereInput | Prisma.AuctionListingItemWhereInput[]
  OR?: Prisma.AuctionListingItemWhereInput[]
  NOT?: Prisma.AuctionListingItemWhereInput | Prisma.AuctionListingItemWhereInput[]
  id?: Prisma.StringFilter<"AuctionListingItem"> | string
  listingId?: Prisma.StringFilter<"AuctionListingItem"> | string
  entityId?: Prisma.StringFilter<"AuctionListingItem"> | string
  name?: Prisma.StringFilter<"AuctionListingItem"> | string
  quantity?: Prisma.IntFilter<"AuctionListingItem"> | number
  uuu?: Prisma.BoolFilter<"AuctionListingItem"> | boolean
  unique?: Prisma.BoolFilter<"AuctionListingItem"> | boolean
  customName?: Prisma.StringNullableFilter<"AuctionListingItem"> | string | null
  customImage?: Prisma.StringNullableFilter<"AuctionListingItem"> | string | null
  imported?: Prisma.BoolFilter<"AuctionListingItem"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AuctionListingItem"> | Date | string
  listing?: Prisma.XOR<Prisma.AuctionListingScalarRelationFilter, Prisma.AuctionListingWhereInput>
  entity?: Prisma.XOR<Prisma.EntityScalarRelationFilter, Prisma.EntityWhereInput>
}

export type AuctionListingItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  uuu?: Prisma.SortOrder
  unique?: Prisma.SortOrder
  customName?: Prisma.SortOrderInput | Prisma.SortOrder
  customImage?: Prisma.SortOrderInput | Prisma.SortOrder
  imported?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  listing?: Prisma.AuctionListingOrderByWithRelationInput
  entity?: Prisma.EntityOrderByWithRelationInput
}

export type AuctionListingItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AuctionListingItemWhereInput | Prisma.AuctionListingItemWhereInput[]
  OR?: Prisma.AuctionListingItemWhereInput[]
  NOT?: Prisma.AuctionListingItemWhereInput | Prisma.AuctionListingItemWhereInput[]
  listingId?: Prisma.StringFilter<"AuctionListingItem"> | string
  entityId?: Prisma.StringFilter<"AuctionListingItem"> | string
  name?: Prisma.StringFilter<"AuctionListingItem"> | string
  quantity?: Prisma.IntFilter<"AuctionListingItem"> | number
  uuu?: Prisma.BoolFilter<"AuctionListingItem"> | boolean
  unique?: Prisma.BoolFilter<"AuctionListingItem"> | boolean
  customName?: Prisma.StringNullableFilter<"AuctionListingItem"> | string | null
  customImage?: Prisma.StringNullableFilter<"AuctionListingItem"> | string | null
  imported?: Prisma.BoolFilter<"AuctionListingItem"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AuctionListingItem"> | Date | string
  listing?: Prisma.XOR<Prisma.AuctionListingScalarRelationFilter, Prisma.AuctionListingWhereInput>
  entity?: Prisma.XOR<Prisma.EntityScalarRelationFilter, Prisma.EntityWhereInput>
}, "id">

export type AuctionListingItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  uuu?: Prisma.SortOrder
  unique?: Prisma.SortOrder
  customName?: Prisma.SortOrderInput | Prisma.SortOrder
  customImage?: Prisma.SortOrderInput | Prisma.SortOrder
  imported?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.AuctionListingItemCountOrderByAggregateInput
  _avg?: Prisma.AuctionListingItemAvgOrderByAggregateInput
  _max?: Prisma.AuctionListingItemMaxOrderByAggregateInput
  _min?: Prisma.AuctionListingItemMinOrderByAggregateInput
  _sum?: Prisma.AuctionListingItemSumOrderByAggregateInput
}

export type AuctionListingItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.AuctionListingItemScalarWhereWithAggregatesInput | Prisma.AuctionListingItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.AuctionListingItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AuctionListingItemScalarWhereWithAggregatesInput | Prisma.AuctionListingItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AuctionListingItem"> | string
  listingId?: Prisma.StringWithAggregatesFilter<"AuctionListingItem"> | string
  entityId?: Prisma.StringWithAggregatesFilter<"AuctionListingItem"> | string
  name?: Prisma.StringWithAggregatesFilter<"AuctionListingItem"> | string
  quantity?: Prisma.IntWithAggregatesFilter<"AuctionListingItem"> | number
  uuu?: Prisma.BoolWithAggregatesFilter<"AuctionListingItem"> | boolean
  unique?: Prisma.BoolWithAggregatesFilter<"AuctionListingItem"> | boolean
  customName?: Prisma.StringNullableWithAggregatesFilter<"AuctionListingItem"> | string | null
  customImage?: Prisma.StringNullableWithAggregatesFilter<"AuctionListingItem"> | string | null
  imported?: Prisma.BoolWithAggregatesFilter<"AuctionListingItem"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"AuctionListingItem"> | Date | string
}

export type AuctionListingItemCreateInput = {
  id?: string
  name: string
  quantity: number
  uuu?: boolean
  unique?: boolean
  customName?: string | null
  customImage?: string | null
  imported?: boolean
  createdAt?: Date | string
  listing: Prisma.AuctionListingCreateNestedOneWithoutItemsInput
  entity: Prisma.EntityCreateNestedOneWithoutAuctionItemsInput
}

export type AuctionListingItemUncheckedCreateInput = {
  id?: string
  listingId: string
  entityId: string
  name: string
  quantity: number
  uuu?: boolean
  unique?: boolean
  customName?: string | null
  customImage?: string | null
  imported?: boolean
  createdAt?: Date | string
}

export type AuctionListingItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  uuu?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unique?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imported?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  listing?: Prisma.AuctionListingUpdateOneRequiredWithoutItemsNestedInput
  entity?: Prisma.EntityUpdateOneRequiredWithoutAuctionItemsNestedInput
}

export type AuctionListingItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  uuu?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unique?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imported?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuctionListingItemCreateManyInput = {
  id?: string
  listingId: string
  entityId: string
  name: string
  quantity: number
  uuu?: boolean
  unique?: boolean
  customName?: string | null
  customImage?: string | null
  imported?: boolean
  createdAt?: Date | string
}

export type AuctionListingItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  uuu?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unique?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imported?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuctionListingItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  uuu?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unique?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imported?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuctionListingItemListRelationFilter = {
  every?: Prisma.AuctionListingItemWhereInput
  some?: Prisma.AuctionListingItemWhereInput
  none?: Prisma.AuctionListingItemWhereInput
}

export type AuctionListingItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AuctionListingItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  uuu?: Prisma.SortOrder
  unique?: Prisma.SortOrder
  customName?: Prisma.SortOrder
  customImage?: Prisma.SortOrder
  imported?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuctionListingItemAvgOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type AuctionListingItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  uuu?: Prisma.SortOrder
  unique?: Prisma.SortOrder
  customName?: Prisma.SortOrder
  customImage?: Prisma.SortOrder
  imported?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuctionListingItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  listingId?: Prisma.SortOrder
  entityId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  quantity?: Prisma.SortOrder
  uuu?: Prisma.SortOrder
  unique?: Prisma.SortOrder
  customName?: Prisma.SortOrder
  customImage?: Prisma.SortOrder
  imported?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type AuctionListingItemSumOrderByAggregateInput = {
  quantity?: Prisma.SortOrder
}

export type AuctionListingItemCreateNestedManyWithoutListingInput = {
  create?: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutListingInput, Prisma.AuctionListingItemUncheckedCreateWithoutListingInput> | Prisma.AuctionListingItemCreateWithoutListingInput[] | Prisma.AuctionListingItemUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.AuctionListingItemCreateOrConnectWithoutListingInput | Prisma.AuctionListingItemCreateOrConnectWithoutListingInput[]
  createMany?: Prisma.AuctionListingItemCreateManyListingInputEnvelope
  connect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
}

export type AuctionListingItemUncheckedCreateNestedManyWithoutListingInput = {
  create?: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutListingInput, Prisma.AuctionListingItemUncheckedCreateWithoutListingInput> | Prisma.AuctionListingItemCreateWithoutListingInput[] | Prisma.AuctionListingItemUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.AuctionListingItemCreateOrConnectWithoutListingInput | Prisma.AuctionListingItemCreateOrConnectWithoutListingInput[]
  createMany?: Prisma.AuctionListingItemCreateManyListingInputEnvelope
  connect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
}

export type AuctionListingItemUpdateManyWithoutListingNestedInput = {
  create?: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutListingInput, Prisma.AuctionListingItemUncheckedCreateWithoutListingInput> | Prisma.AuctionListingItemCreateWithoutListingInput[] | Prisma.AuctionListingItemUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.AuctionListingItemCreateOrConnectWithoutListingInput | Prisma.AuctionListingItemCreateOrConnectWithoutListingInput[]
  upsert?: Prisma.AuctionListingItemUpsertWithWhereUniqueWithoutListingInput | Prisma.AuctionListingItemUpsertWithWhereUniqueWithoutListingInput[]
  createMany?: Prisma.AuctionListingItemCreateManyListingInputEnvelope
  set?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  disconnect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  delete?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  connect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  update?: Prisma.AuctionListingItemUpdateWithWhereUniqueWithoutListingInput | Prisma.AuctionListingItemUpdateWithWhereUniqueWithoutListingInput[]
  updateMany?: Prisma.AuctionListingItemUpdateManyWithWhereWithoutListingInput | Prisma.AuctionListingItemUpdateManyWithWhereWithoutListingInput[]
  deleteMany?: Prisma.AuctionListingItemScalarWhereInput | Prisma.AuctionListingItemScalarWhereInput[]
}

export type AuctionListingItemUncheckedUpdateManyWithoutListingNestedInput = {
  create?: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutListingInput, Prisma.AuctionListingItemUncheckedCreateWithoutListingInput> | Prisma.AuctionListingItemCreateWithoutListingInput[] | Prisma.AuctionListingItemUncheckedCreateWithoutListingInput[]
  connectOrCreate?: Prisma.AuctionListingItemCreateOrConnectWithoutListingInput | Prisma.AuctionListingItemCreateOrConnectWithoutListingInput[]
  upsert?: Prisma.AuctionListingItemUpsertWithWhereUniqueWithoutListingInput | Prisma.AuctionListingItemUpsertWithWhereUniqueWithoutListingInput[]
  createMany?: Prisma.AuctionListingItemCreateManyListingInputEnvelope
  set?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  disconnect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  delete?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  connect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  update?: Prisma.AuctionListingItemUpdateWithWhereUniqueWithoutListingInput | Prisma.AuctionListingItemUpdateWithWhereUniqueWithoutListingInput[]
  updateMany?: Prisma.AuctionListingItemUpdateManyWithWhereWithoutListingInput | Prisma.AuctionListingItemUpdateManyWithWhereWithoutListingInput[]
  deleteMany?: Prisma.AuctionListingItemScalarWhereInput | Prisma.AuctionListingItemScalarWhereInput[]
}

export type AuctionListingItemCreateNestedManyWithoutEntityInput = {
  create?: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutEntityInput, Prisma.AuctionListingItemUncheckedCreateWithoutEntityInput> | Prisma.AuctionListingItemCreateWithoutEntityInput[] | Prisma.AuctionListingItemUncheckedCreateWithoutEntityInput[]
  connectOrCreate?: Prisma.AuctionListingItemCreateOrConnectWithoutEntityInput | Prisma.AuctionListingItemCreateOrConnectWithoutEntityInput[]
  createMany?: Prisma.AuctionListingItemCreateManyEntityInputEnvelope
  connect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
}

export type AuctionListingItemUncheckedCreateNestedManyWithoutEntityInput = {
  create?: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutEntityInput, Prisma.AuctionListingItemUncheckedCreateWithoutEntityInput> | Prisma.AuctionListingItemCreateWithoutEntityInput[] | Prisma.AuctionListingItemUncheckedCreateWithoutEntityInput[]
  connectOrCreate?: Prisma.AuctionListingItemCreateOrConnectWithoutEntityInput | Prisma.AuctionListingItemCreateOrConnectWithoutEntityInput[]
  createMany?: Prisma.AuctionListingItemCreateManyEntityInputEnvelope
  connect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
}

export type AuctionListingItemUpdateManyWithoutEntityNestedInput = {
  create?: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutEntityInput, Prisma.AuctionListingItemUncheckedCreateWithoutEntityInput> | Prisma.AuctionListingItemCreateWithoutEntityInput[] | Prisma.AuctionListingItemUncheckedCreateWithoutEntityInput[]
  connectOrCreate?: Prisma.AuctionListingItemCreateOrConnectWithoutEntityInput | Prisma.AuctionListingItemCreateOrConnectWithoutEntityInput[]
  upsert?: Prisma.AuctionListingItemUpsertWithWhereUniqueWithoutEntityInput | Prisma.AuctionListingItemUpsertWithWhereUniqueWithoutEntityInput[]
  createMany?: Prisma.AuctionListingItemCreateManyEntityInputEnvelope
  set?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  disconnect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  delete?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  connect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  update?: Prisma.AuctionListingItemUpdateWithWhereUniqueWithoutEntityInput | Prisma.AuctionListingItemUpdateWithWhereUniqueWithoutEntityInput[]
  updateMany?: Prisma.AuctionListingItemUpdateManyWithWhereWithoutEntityInput | Prisma.AuctionListingItemUpdateManyWithWhereWithoutEntityInput[]
  deleteMany?: Prisma.AuctionListingItemScalarWhereInput | Prisma.AuctionListingItemScalarWhereInput[]
}

export type AuctionListingItemUncheckedUpdateManyWithoutEntityNestedInput = {
  create?: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutEntityInput, Prisma.AuctionListingItemUncheckedCreateWithoutEntityInput> | Prisma.AuctionListingItemCreateWithoutEntityInput[] | Prisma.AuctionListingItemUncheckedCreateWithoutEntityInput[]
  connectOrCreate?: Prisma.AuctionListingItemCreateOrConnectWithoutEntityInput | Prisma.AuctionListingItemCreateOrConnectWithoutEntityInput[]
  upsert?: Prisma.AuctionListingItemUpsertWithWhereUniqueWithoutEntityInput | Prisma.AuctionListingItemUpsertWithWhereUniqueWithoutEntityInput[]
  createMany?: Prisma.AuctionListingItemCreateManyEntityInputEnvelope
  set?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  disconnect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  delete?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  connect?: Prisma.AuctionListingItemWhereUniqueInput | Prisma.AuctionListingItemWhereUniqueInput[]
  update?: Prisma.AuctionListingItemUpdateWithWhereUniqueWithoutEntityInput | Prisma.AuctionListingItemUpdateWithWhereUniqueWithoutEntityInput[]
  updateMany?: Prisma.AuctionListingItemUpdateManyWithWhereWithoutEntityInput | Prisma.AuctionListingItemUpdateManyWithWhereWithoutEntityInput[]
  deleteMany?: Prisma.AuctionListingItemScalarWhereInput | Prisma.AuctionListingItemScalarWhereInput[]
}

export type AuctionListingItemCreateWithoutListingInput = {
  id?: string
  name: string
  quantity: number
  uuu?: boolean
  unique?: boolean
  customName?: string | null
  customImage?: string | null
  imported?: boolean
  createdAt?: Date | string
  entity: Prisma.EntityCreateNestedOneWithoutAuctionItemsInput
}

export type AuctionListingItemUncheckedCreateWithoutListingInput = {
  id?: string
  entityId: string
  name: string
  quantity: number
  uuu?: boolean
  unique?: boolean
  customName?: string | null
  customImage?: string | null
  imported?: boolean
  createdAt?: Date | string
}

export type AuctionListingItemCreateOrConnectWithoutListingInput = {
  where: Prisma.AuctionListingItemWhereUniqueInput
  create: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutListingInput, Prisma.AuctionListingItemUncheckedCreateWithoutListingInput>
}

export type AuctionListingItemCreateManyListingInputEnvelope = {
  data: Prisma.AuctionListingItemCreateManyListingInput | Prisma.AuctionListingItemCreateManyListingInput[]
  skipDuplicates?: boolean
}

export type AuctionListingItemUpsertWithWhereUniqueWithoutListingInput = {
  where: Prisma.AuctionListingItemWhereUniqueInput
  update: Prisma.XOR<Prisma.AuctionListingItemUpdateWithoutListingInput, Prisma.AuctionListingItemUncheckedUpdateWithoutListingInput>
  create: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutListingInput, Prisma.AuctionListingItemUncheckedCreateWithoutListingInput>
}

export type AuctionListingItemUpdateWithWhereUniqueWithoutListingInput = {
  where: Prisma.AuctionListingItemWhereUniqueInput
  data: Prisma.XOR<Prisma.AuctionListingItemUpdateWithoutListingInput, Prisma.AuctionListingItemUncheckedUpdateWithoutListingInput>
}

export type AuctionListingItemUpdateManyWithWhereWithoutListingInput = {
  where: Prisma.AuctionListingItemScalarWhereInput
  data: Prisma.XOR<Prisma.AuctionListingItemUpdateManyMutationInput, Prisma.AuctionListingItemUncheckedUpdateManyWithoutListingInput>
}

export type AuctionListingItemScalarWhereInput = {
  AND?: Prisma.AuctionListingItemScalarWhereInput | Prisma.AuctionListingItemScalarWhereInput[]
  OR?: Prisma.AuctionListingItemScalarWhereInput[]
  NOT?: Prisma.AuctionListingItemScalarWhereInput | Prisma.AuctionListingItemScalarWhereInput[]
  id?: Prisma.StringFilter<"AuctionListingItem"> | string
  listingId?: Prisma.StringFilter<"AuctionListingItem"> | string
  entityId?: Prisma.StringFilter<"AuctionListingItem"> | string
  name?: Prisma.StringFilter<"AuctionListingItem"> | string
  quantity?: Prisma.IntFilter<"AuctionListingItem"> | number
  uuu?: Prisma.BoolFilter<"AuctionListingItem"> | boolean
  unique?: Prisma.BoolFilter<"AuctionListingItem"> | boolean
  customName?: Prisma.StringNullableFilter<"AuctionListingItem"> | string | null
  customImage?: Prisma.StringNullableFilter<"AuctionListingItem"> | string | null
  imported?: Prisma.BoolFilter<"AuctionListingItem"> | boolean
  createdAt?: Prisma.DateTimeFilter<"AuctionListingItem"> | Date | string
}

export type AuctionListingItemCreateWithoutEntityInput = {
  id?: string
  name: string
  quantity: number
  uuu?: boolean
  unique?: boolean
  customName?: string | null
  customImage?: string | null
  imported?: boolean
  createdAt?: Date | string
  listing: Prisma.AuctionListingCreateNestedOneWithoutItemsInput
}

export type AuctionListingItemUncheckedCreateWithoutEntityInput = {
  id?: string
  listingId: string
  name: string
  quantity: number
  uuu?: boolean
  unique?: boolean
  customName?: string | null
  customImage?: string | null
  imported?: boolean
  createdAt?: Date | string
}

export type AuctionListingItemCreateOrConnectWithoutEntityInput = {
  where: Prisma.AuctionListingItemWhereUniqueInput
  create: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutEntityInput, Prisma.AuctionListingItemUncheckedCreateWithoutEntityInput>
}

export type AuctionListingItemCreateManyEntityInputEnvelope = {
  data: Prisma.AuctionListingItemCreateManyEntityInput | Prisma.AuctionListingItemCreateManyEntityInput[]
  skipDuplicates?: boolean
}

export type AuctionListingItemUpsertWithWhereUniqueWithoutEntityInput = {
  where: Prisma.AuctionListingItemWhereUniqueInput
  update: Prisma.XOR<Prisma.AuctionListingItemUpdateWithoutEntityInput, Prisma.AuctionListingItemUncheckedUpdateWithoutEntityInput>
  create: Prisma.XOR<Prisma.AuctionListingItemCreateWithoutEntityInput, Prisma.AuctionListingItemUncheckedCreateWithoutEntityInput>
}

export type AuctionListingItemUpdateWithWhereUniqueWithoutEntityInput = {
  where: Prisma.AuctionListingItemWhereUniqueInput
  data: Prisma.XOR<Prisma.AuctionListingItemUpdateWithoutEntityInput, Prisma.AuctionListingItemUncheckedUpdateWithoutEntityInput>
}

export type AuctionListingItemUpdateManyWithWhereWithoutEntityInput = {
  where: Prisma.AuctionListingItemScalarWhereInput
  data: Prisma.XOR<Prisma.AuctionListingItemUpdateManyMutationInput, Prisma.AuctionListingItemUncheckedUpdateManyWithoutEntityInput>
}

export type AuctionListingItemCreateManyListingInput = {
  id?: string
  entityId: string
  name: string
  quantity: number
  uuu?: boolean
  unique?: boolean
  customName?: string | null
  customImage?: string | null
  imported?: boolean
  createdAt?: Date | string
}

export type AuctionListingItemUpdateWithoutListingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  uuu?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unique?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imported?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  entity?: Prisma.EntityUpdateOneRequiredWithoutAuctionItemsNestedInput
}

export type AuctionListingItemUncheckedUpdateWithoutListingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  uuu?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unique?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imported?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuctionListingItemUncheckedUpdateManyWithoutListingInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  entityId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  uuu?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unique?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imported?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuctionListingItemCreateManyEntityInput = {
  id?: string
  listingId: string
  name: string
  quantity: number
  uuu?: boolean
  unique?: boolean
  customName?: string | null
  customImage?: string | null
  imported?: boolean
  createdAt?: Date | string
}

export type AuctionListingItemUpdateWithoutEntityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  uuu?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unique?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imported?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  listing?: Prisma.AuctionListingUpdateOneRequiredWithoutItemsNestedInput
}

export type AuctionListingItemUncheckedUpdateWithoutEntityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  uuu?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unique?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imported?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AuctionListingItemUncheckedUpdateManyWithoutEntityInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  listingId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  quantity?: Prisma.IntFieldUpdateOperationsInput | number
  uuu?: Prisma.BoolFieldUpdateOperationsInput | boolean
  unique?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customImage?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  imported?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type AuctionListingItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  listingId?: boolean
  entityId?: boolean
  name?: boolean
  quantity?: boolean
  uuu?: boolean
  unique?: boolean
  customName?: boolean
  customImage?: boolean
  imported?: boolean
  createdAt?: boolean
  listing?: boolean | Prisma.AuctionListingDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}, ExtArgs["result"]["auctionListingItem"]>

export type AuctionListingItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  listingId?: boolean
  entityId?: boolean
  name?: boolean
  quantity?: boolean
  uuu?: boolean
  unique?: boolean
  customName?: boolean
  customImage?: boolean
  imported?: boolean
  createdAt?: boolean
  listing?: boolean | Prisma.AuctionListingDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}, ExtArgs["result"]["auctionListingItem"]>

export type AuctionListingItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  listingId?: boolean
  entityId?: boolean
  name?: boolean
  quantity?: boolean
  uuu?: boolean
  unique?: boolean
  customName?: boolean
  customImage?: boolean
  imported?: boolean
  createdAt?: boolean
  listing?: boolean | Prisma.AuctionListingDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}, ExtArgs["result"]["auctionListingItem"]>

export type AuctionListingItemSelectScalar = {
  id?: boolean
  listingId?: boolean
  entityId?: boolean
  name?: boolean
  quantity?: boolean
  uuu?: boolean
  unique?: boolean
  customName?: boolean
  customImage?: boolean
  imported?: boolean
  createdAt?: boolean
}

export type AuctionListingItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "listingId" | "entityId" | "name" | "quantity" | "uuu" | "unique" | "customName" | "customImage" | "imported" | "createdAt", ExtArgs["result"]["auctionListingItem"]>
export type AuctionListingItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  listing?: boolean | Prisma.AuctionListingDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}
export type AuctionListingItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  listing?: boolean | Prisma.AuctionListingDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}
export type AuctionListingItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  listing?: boolean | Prisma.AuctionListingDefaultArgs<ExtArgs>
  entity?: boolean | Prisma.EntityDefaultArgs<ExtArgs>
}

export type $AuctionListingItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AuctionListingItem"
  objects: {
    listing: Prisma.$AuctionListingPayload<ExtArgs>
    entity: Prisma.$EntityPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    listingId: string
    entityId: string
    name: string
    quantity: number
    uuu: boolean
    unique: boolean
    customName: string | null
    customImage: string | null
    imported: boolean
    createdAt: Date
  }, ExtArgs["result"]["auctionListingItem"]>
  composites: {}
}

export type AuctionListingItemGetPayload<S extends boolean | null | undefined | AuctionListingItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload, S>

export type AuctionListingItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AuctionListingItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: AuctionListingItemCountAggregateInputType | true
  }

export interface AuctionListingItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AuctionListingItem'], meta: { name: 'AuctionListingItem' } }
  /**
   * Find zero or one AuctionListingItem that matches the filter.
   * @param {AuctionListingItemFindUniqueArgs} args - Arguments to find a AuctionListingItem
   * @example
   * // Get one AuctionListingItem
   * const auctionListingItem = await prisma.auctionListingItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AuctionListingItemFindUniqueArgs>(args: Prisma.SelectSubset<T, AuctionListingItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AuctionListingItemClient<runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AuctionListingItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AuctionListingItemFindUniqueOrThrowArgs} args - Arguments to find a AuctionListingItem
   * @example
   * // Get one AuctionListingItem
   * const auctionListingItem = await prisma.auctionListingItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AuctionListingItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AuctionListingItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuctionListingItemClient<runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuctionListingItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuctionListingItemFindFirstArgs} args - Arguments to find a AuctionListingItem
   * @example
   * // Get one AuctionListingItem
   * const auctionListingItem = await prisma.auctionListingItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AuctionListingItemFindFirstArgs>(args?: Prisma.SelectSubset<T, AuctionListingItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__AuctionListingItemClient<runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AuctionListingItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuctionListingItemFindFirstOrThrowArgs} args - Arguments to find a AuctionListingItem
   * @example
   * // Get one AuctionListingItem
   * const auctionListingItem = await prisma.auctionListingItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AuctionListingItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AuctionListingItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AuctionListingItemClient<runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AuctionListingItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuctionListingItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AuctionListingItems
   * const auctionListingItems = await prisma.auctionListingItem.findMany()
   * 
   * // Get first 10 AuctionListingItems
   * const auctionListingItems = await prisma.auctionListingItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const auctionListingItemWithIdOnly = await prisma.auctionListingItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AuctionListingItemFindManyArgs>(args?: Prisma.SelectSubset<T, AuctionListingItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AuctionListingItem.
   * @param {AuctionListingItemCreateArgs} args - Arguments to create a AuctionListingItem.
   * @example
   * // Create one AuctionListingItem
   * const AuctionListingItem = await prisma.auctionListingItem.create({
   *   data: {
   *     // ... data to create a AuctionListingItem
   *   }
   * })
   * 
   */
  create<T extends AuctionListingItemCreateArgs>(args: Prisma.SelectSubset<T, AuctionListingItemCreateArgs<ExtArgs>>): Prisma.Prisma__AuctionListingItemClient<runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AuctionListingItems.
   * @param {AuctionListingItemCreateManyArgs} args - Arguments to create many AuctionListingItems.
   * @example
   * // Create many AuctionListingItems
   * const auctionListingItem = await prisma.auctionListingItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AuctionListingItemCreateManyArgs>(args?: Prisma.SelectSubset<T, AuctionListingItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AuctionListingItems and returns the data saved in the database.
   * @param {AuctionListingItemCreateManyAndReturnArgs} args - Arguments to create many AuctionListingItems.
   * @example
   * // Create many AuctionListingItems
   * const auctionListingItem = await prisma.auctionListingItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AuctionListingItems and only return the `id`
   * const auctionListingItemWithIdOnly = await prisma.auctionListingItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AuctionListingItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AuctionListingItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AuctionListingItem.
   * @param {AuctionListingItemDeleteArgs} args - Arguments to delete one AuctionListingItem.
   * @example
   * // Delete one AuctionListingItem
   * const AuctionListingItem = await prisma.auctionListingItem.delete({
   *   where: {
   *     // ... filter to delete one AuctionListingItem
   *   }
   * })
   * 
   */
  delete<T extends AuctionListingItemDeleteArgs>(args: Prisma.SelectSubset<T, AuctionListingItemDeleteArgs<ExtArgs>>): Prisma.Prisma__AuctionListingItemClient<runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AuctionListingItem.
   * @param {AuctionListingItemUpdateArgs} args - Arguments to update one AuctionListingItem.
   * @example
   * // Update one AuctionListingItem
   * const auctionListingItem = await prisma.auctionListingItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AuctionListingItemUpdateArgs>(args: Prisma.SelectSubset<T, AuctionListingItemUpdateArgs<ExtArgs>>): Prisma.Prisma__AuctionListingItemClient<runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AuctionListingItems.
   * @param {AuctionListingItemDeleteManyArgs} args - Arguments to filter AuctionListingItems to delete.
   * @example
   * // Delete a few AuctionListingItems
   * const { count } = await prisma.auctionListingItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AuctionListingItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, AuctionListingItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuctionListingItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuctionListingItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AuctionListingItems
   * const auctionListingItem = await prisma.auctionListingItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AuctionListingItemUpdateManyArgs>(args: Prisma.SelectSubset<T, AuctionListingItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AuctionListingItems and returns the data updated in the database.
   * @param {AuctionListingItemUpdateManyAndReturnArgs} args - Arguments to update many AuctionListingItems.
   * @example
   * // Update many AuctionListingItems
   * const auctionListingItem = await prisma.auctionListingItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AuctionListingItems and only return the `id`
   * const auctionListingItemWithIdOnly = await prisma.auctionListingItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AuctionListingItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AuctionListingItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AuctionListingItem.
   * @param {AuctionListingItemUpsertArgs} args - Arguments to update or create a AuctionListingItem.
   * @example
   * // Update or create a AuctionListingItem
   * const auctionListingItem = await prisma.auctionListingItem.upsert({
   *   create: {
   *     // ... data to create a AuctionListingItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AuctionListingItem we want to update
   *   }
   * })
   */
  upsert<T extends AuctionListingItemUpsertArgs>(args: Prisma.SelectSubset<T, AuctionListingItemUpsertArgs<ExtArgs>>): Prisma.Prisma__AuctionListingItemClient<runtime.Types.Result.GetResult<Prisma.$AuctionListingItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AuctionListingItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuctionListingItemCountArgs} args - Arguments to filter AuctionListingItems to count.
   * @example
   * // Count the number of AuctionListingItems
   * const count = await prisma.auctionListingItem.count({
   *   where: {
   *     // ... the filter for the AuctionListingItems we want to count
   *   }
   * })
  **/
  count<T extends AuctionListingItemCountArgs>(
    args?: Prisma.Subset<T, AuctionListingItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AuctionListingItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AuctionListingItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuctionListingItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AuctionListingItemAggregateArgs>(args: Prisma.Subset<T, AuctionListingItemAggregateArgs>): Prisma.PrismaPromise<GetAuctionListingItemAggregateType<T>>

  /**
   * Group by AuctionListingItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AuctionListingItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AuctionListingItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AuctionListingItemGroupByArgs['orderBy'] }
      : { orderBy?: AuctionListingItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AuctionListingItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAuctionListingItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AuctionListingItem model
 */
readonly fields: AuctionListingItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AuctionListingItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AuctionListingItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  listing<T extends Prisma.AuctionListingDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AuctionListingDefaultArgs<ExtArgs>>): Prisma.Prisma__AuctionListingClient<runtime.Types.Result.GetResult<Prisma.$AuctionListingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  entity<T extends Prisma.EntityDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.EntityDefaultArgs<ExtArgs>>): Prisma.Prisma__EntityClient<runtime.Types.Result.GetResult<Prisma.$EntityPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AuctionListingItem model
 */
export interface AuctionListingItemFieldRefs {
  readonly id: Prisma.FieldRef<"AuctionListingItem", 'String'>
  readonly listingId: Prisma.FieldRef<"AuctionListingItem", 'String'>
  readonly entityId: Prisma.FieldRef<"AuctionListingItem", 'String'>
  readonly name: Prisma.FieldRef<"AuctionListingItem", 'String'>
  readonly quantity: Prisma.FieldRef<"AuctionListingItem", 'Int'>
  readonly uuu: Prisma.FieldRef<"AuctionListingItem", 'Boolean'>
  readonly unique: Prisma.FieldRef<"AuctionListingItem", 'Boolean'>
  readonly customName: Prisma.FieldRef<"AuctionListingItem", 'String'>
  readonly customImage: Prisma.FieldRef<"AuctionListingItem", 'String'>
  readonly imported: Prisma.FieldRef<"AuctionListingItem", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"AuctionListingItem", 'DateTime'>
}
    

// Custom InputTypes
/**
 * AuctionListingItem findUnique
 */
export type AuctionListingItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemInclude<ExtArgs> | null
  /**
   * Filter, which AuctionListingItem to fetch.
   */
  where: Prisma.AuctionListingItemWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuctionListingItem findUniqueOrThrow
 */
export type AuctionListingItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemInclude<ExtArgs> | null
  /**
   * Filter, which AuctionListingItem to fetch.
   */
  where: Prisma.AuctionListingItemWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuctionListingItem findFirst
 */
export type AuctionListingItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemInclude<ExtArgs> | null
  /**
   * Filter, which AuctionListingItem to fetch.
   */
  where?: Prisma.AuctionListingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuctionListingItems to fetch.
   */
  orderBy?: Prisma.AuctionListingItemOrderByWithRelationInput | Prisma.AuctionListingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuctionListingItems.
   */
  cursor?: Prisma.AuctionListingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuctionListingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuctionListingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuctionListingItems.
   */
  distinct?: Prisma.AuctionListingItemScalarFieldEnum | Prisma.AuctionListingItemScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuctionListingItem findFirstOrThrow
 */
export type AuctionListingItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemInclude<ExtArgs> | null
  /**
   * Filter, which AuctionListingItem to fetch.
   */
  where?: Prisma.AuctionListingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuctionListingItems to fetch.
   */
  orderBy?: Prisma.AuctionListingItemOrderByWithRelationInput | Prisma.AuctionListingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AuctionListingItems.
   */
  cursor?: Prisma.AuctionListingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuctionListingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuctionListingItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AuctionListingItems.
   */
  distinct?: Prisma.AuctionListingItemScalarFieldEnum | Prisma.AuctionListingItemScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuctionListingItem findMany
 */
export type AuctionListingItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemInclude<ExtArgs> | null
  /**
   * Filter, which AuctionListingItems to fetch.
   */
  where?: Prisma.AuctionListingItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AuctionListingItems to fetch.
   */
  orderBy?: Prisma.AuctionListingItemOrderByWithRelationInput | Prisma.AuctionListingItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AuctionListingItems.
   */
  cursor?: Prisma.AuctionListingItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AuctionListingItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AuctionListingItems.
   */
  skip?: number
  distinct?: Prisma.AuctionListingItemScalarFieldEnum | Prisma.AuctionListingItemScalarFieldEnum[]
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuctionListingItem create
 */
export type AuctionListingItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemInclude<ExtArgs> | null
  /**
   * The data needed to create a AuctionListingItem.
   */
  data: Prisma.XOR<Prisma.AuctionListingItemCreateInput, Prisma.AuctionListingItemUncheckedCreateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuctionListingItem createMany
 */
export type AuctionListingItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AuctionListingItems.
   */
  data: Prisma.AuctionListingItemCreateManyInput | Prisma.AuctionListingItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AuctionListingItem createManyAndReturn
 */
export type AuctionListingItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * The data used to create many AuctionListingItems.
   */
  data: Prisma.AuctionListingItemCreateManyInput | Prisma.AuctionListingItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AuctionListingItem update
 */
export type AuctionListingItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemInclude<ExtArgs> | null
  /**
   * The data needed to update a AuctionListingItem.
   */
  data: Prisma.XOR<Prisma.AuctionListingItemUpdateInput, Prisma.AuctionListingItemUncheckedUpdateInput>
  /**
   * Choose, which AuctionListingItem to update.
   */
  where: Prisma.AuctionListingItemWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuctionListingItem updateMany
 */
export type AuctionListingItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AuctionListingItems.
   */
  data: Prisma.XOR<Prisma.AuctionListingItemUpdateManyMutationInput, Prisma.AuctionListingItemUncheckedUpdateManyInput>
  /**
   * Filter which AuctionListingItems to update
   */
  where?: Prisma.AuctionListingItemWhereInput
  /**
   * Limit how many AuctionListingItems to update.
   */
  limit?: number
}

/**
 * AuctionListingItem updateManyAndReturn
 */
export type AuctionListingItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * The data used to update AuctionListingItems.
   */
  data: Prisma.XOR<Prisma.AuctionListingItemUpdateManyMutationInput, Prisma.AuctionListingItemUncheckedUpdateManyInput>
  /**
   * Filter which AuctionListingItems to update
   */
  where?: Prisma.AuctionListingItemWhereInput
  /**
   * Limit how many AuctionListingItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AuctionListingItem upsert
 */
export type AuctionListingItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemInclude<ExtArgs> | null
  /**
   * The filter to search for the AuctionListingItem to update in case it exists.
   */
  where: Prisma.AuctionListingItemWhereUniqueInput
  /**
   * In case the AuctionListingItem found by the `where` argument doesn't exist, create a new AuctionListingItem with this data.
   */
  create: Prisma.XOR<Prisma.AuctionListingItemCreateInput, Prisma.AuctionListingItemUncheckedCreateInput>
  /**
   * In case the AuctionListingItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AuctionListingItemUpdateInput, Prisma.AuctionListingItemUncheckedUpdateInput>
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuctionListingItem delete
 */
export type AuctionListingItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemInclude<ExtArgs> | null
  /**
   * Filter which AuctionListingItem to delete.
   */
  where: Prisma.AuctionListingItemWhereUniqueInput
  relationLoadStrategy?: Prisma.RelationLoadStrategy
}

/**
 * AuctionListingItem deleteMany
 */
export type AuctionListingItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AuctionListingItems to delete
   */
  where?: Prisma.AuctionListingItemWhereInput
  /**
   * Limit how many AuctionListingItems to delete.
   */
  limit?: number
}

/**
 * AuctionListingItem without action
 */
export type AuctionListingItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AuctionListingItem
   */
  select?: Prisma.AuctionListingItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AuctionListingItem
   */
  omit?: Prisma.AuctionListingItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AuctionListingItemInclude<ExtArgs> | null
}
