name: Lint Check

on:
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm lint