name: Deploy to Staging

on:
  push:
    branches:
      - main

permissions:
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./apps/market/Dockerfile
          push: true
          tags: ghcr.io/swc-unnamed/market:latest

      - name: Deploy to Staging
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'

  sync-notifications:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Wait 5 minutes before syncing
        run: sleep 300

      - name: Sync Notifications
        uses: novuhq/actions-novu-sync@v2
        with:
          secret-key: ${{ secrets.NOVU_DEV_SECRET_KEY }}
          bridge-url: ${{ secrets.NOVU_DEV_BRIDGE_URL }}
          api-url: ${{ secrets.NOVU_API_URL }}
